"""Structural ports used by the frontend-neutral application service."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from .catalog import CatalogSnapshot
from .config import ToolConfig
from .procs import ToolStatus


class CatalogPort(Protocol):
    """Persistence operations required by :class:`ToolDeckApplication`."""

    def refresh(self) -> CatalogSnapshot: ...

    def snapshot(self) -> CatalogSnapshot: ...

    def find(self, tool_id: str) -> ToolConfig: ...

    def save_tool(self, tool: ToolConfig, *, overwrite: bool = True) -> CatalogSnapshot: ...

    def delete_tool(self, tool_id: str) -> ToolConfig: ...

    def import_tool(self, source: Path, *, overwrite: bool = False) -> ToolConfig: ...

    def move_tool(self, tool_id: str, target_group: str, target_index: int) -> bool: ...

    def move_group(self, group: str, target_index: int) -> bool: ...

    def set_group_collapsed(self, group: str, collapsed: bool) -> bool: ...

    def toggle_group(self, group: str) -> bool: ...


class RuntimePort(Protocol):
    """Process lifecycle operations consumed by the application service."""

    def tick(self) -> None: ...

    def status(self, tool_id: str) -> ToolStatus: ...

    def start(self, tool: ToolConfig) -> ToolStatus: ...

    def stop_begin(self, tool: ToolConfig) -> ToolStatus: ...

    def stop_blocking(self, tool: ToolConfig) -> ToolStatus: ...

    def stop_all_begin(self, tools: dict[str, ToolConfig]) -> list[str]: ...
